django_movie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('movie.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.MoviesView.as_view()),
    path("filter/", views.FilterMoviesView.as_view(), name='filter'),
    path('<slug:slug>/', views.MovieDetailView.as_view(), name='moviesingle'),
    path('review/<int:pk>/', views.AddReviews.as_view(), name='add_review'),
    path('actor/<str:slug>/', views.ActorView.as_view(), name='actor_detail'),
]

movie/models.py
from django.db import models
from datetime import date
from django.urls import reverse


class Category(models.Model):
    name = models.CharField("Категория", max_length=150)
    description = models.TextField("Описание")
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Actor(models.Model):
    name = models.CharField("Имя", max_length=100)
    age = models.PositiveSmallIntegerField("Возраст", default=0)
    description = models.TextField("Описание")
    image = models.ImageField('Изображение', upload_to='actors/')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('actor_detail', kwargs={'slug': self.name})

    class Meta:
        verbose_name = 'Актеры и режиссеры'
        verbose_name_plural = 'Актеры и режиссеры'


class Genre(models.Model):
    name = models.CharField("Жанр", max_length=100)
    description = models.TextField("Описание")
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'


class Movie(models.Model):
    title = models.CharField("Название", max_length=100)
    tagline = models.CharField("Слоган", max_length=100, default='')
    description = models.TextField("Описание")
    poster = models.ImageField('Постер', upload_to='movies/')
    year = models.PositiveSmallIntegerField("Дата выхода", default=2019)
    country = models.CharField("Страна", max_length=30)
    directors = models.ManyToManyField(Actor, verbose_name='режиссер', related_name='film_director')
    actors = models.ManyToManyField(Actor, verbose_name='актеры', related_name='film_actor')
    genre = models.ManyToManyField(Genre, verbose_name='жанры')
    world_premiere = models.DateField('Премьера в мире', default=date.today)
    budget = models.PositiveIntegerField('Бюджет', default=0, help_text='Указывать в долларах')
    fees_to_usa = models.PositiveIntegerField('Сборы в США',  default=0, help_text='Указывать в долларах')
    fees_to_world = models.PositiveIntegerField('Сборы в Мире',  default=0, help_text='Указывать в долларах')
    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.SET_NULL, null=True)
    url = models.SlugField(max_length=160, unique=True)
    draft = models.BooleanField("Черновик", default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('moviesingle', kwargs={'slug': self.url})

    class Meta:
        verbose_name = 'Фильм'
        verbose_name_plural = 'Фильмы'


class MovieShots(models.Model):
    title = models.CharField("Заголовок", max_length=100)
    description = models.TextField("Описание")
    image = models.ImageField('Изображение', upload_to='actors/')
    movie = models.ForeignKey(Movie, verbose_name='Фильм', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Кадр из фильма'
        verbose_name_plural = 'Кадры из фильма'


class RatingStar(models.Model):
    value = models.SmallIntegerField('Значение', default=0)

    def __str__(self):
        return self.value

    class Meta:
        verbose_name = 'Звезда рейтинга'
        verbose_name_plural = 'Звезды рейтинга'


class Rating(models.Model):
    ip = models.CharField('Ip адрес', max_length=15)
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE, verbose_name='звезда')
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name='фильм')

    def __str__(self):
        return f'{self.star} - {self.movie}'

    class Meta:
        verbose_name = 'Рейтинг'
        verbose_name_plural = 'Рейтинги'


class Reviews(models.Model):
    email = models.EmailField()
    name = models.CharField("Имя", max_length=100)
    text = models.TextField("Сообщение", max_length=5000)
    parent = models.ForeignKey('self', verbose_name='Родитель',
                               on_delete=models.SET_NULL, blank=True, null=True)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name='фильм', related_name='reviews')

    def __str__(self):
        return f'{self.name} - {self.movie}'

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

movie/forms.py
from django import forms
from .models import Reviews


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Reviews
        fields = ['name', 'email', 'text']

movie/views.py
from django.db.models import Q
from django.shortcuts import render, redirect
from django.views.generic.base import View
from django.views.generic import ListView, DetailView
from .models import Movie, Category, Actor, Genre
from .forms import ReviewForm


class GenreYear:
    def get_genres(self):
        return Genre.objects.all()

    def get_years(self):
        return Movie.objects.filter(draft=False).values('year')


class MoviesView(GenreYear, ListView):
    model = Movie
    queryset = Movie.objects.filter(draft=False)
    template_name = 'html/movies.html'

    # def get_context_data(self, *args, **kwargs):
    #     context = super().get_context_data(*args, **kwargs)
    #     context['categories'] = Category.objects.all()
    #     return context


class MovieDetailView(GenreYear, DetailView):
    model = Movie
    template_name = 'html/moviesingle.html'
    slug_field = 'url'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['categories'] = Category.objects.all()
        return context


class AddReviews(View):
    def post(self, request, pk):
        form = ReviewForm(request.POST)
        movie = Movie.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            if request.POST.get('parent', None):
                form.parent_id = int(request.POST.get('parent'))
            form.movie = movie
            form.save()
        return redirect(movie.get_absolute_url())


class ActorView(GenreYear, DetailView):
    model = Actor
    template_name = 'html/actor.html'
    slug_field = 'name'


class FilterMoviesView(GenreYear, ListView):
    template_name = 'html/movies.html'

    def get_queryset(self):
        queryset = Movie.objects.filter(
            Q(year__in=self.request.GET.getlist("year")) |
            Q(genres__in=self.request.GET.getlist("genre"))
        ).distinct()
        return queryset

movie/templates/html/actor.html
{% extends 'html/layout.html' %}
{% load static %}
{% block title %}Актёр{% endblock %}

{% block banner %}
<div class="main-banner bg bg1" id="home" style="background-color: rgba(0, 0, 0, 0); margin-top: 0px; background-image:
  url({% static 'images/banner.jpg' %});">
{% endblock %}

{% block content %}

                <!-- //product left -->
                <!-- product right -->
    <div class="left-ads-display col-lg-8">
        <div class="row">
            <div class="desc1-left col-md-6">
                <img src="{{ actor.image.url }}" class="img-fluid" alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <h3 class="editContent" style="outline: none; cursor: inherit;">
                    {{ actor.title }}</h3>
                <h5 class="editContent"></h5>
                <ul>
                    <li><span><b>Возраст:</b> {{ actor.age }} лет</span></li>
                    <li>
                        <span><b>Режиссер:</b>
                            {% for movie in actor.film_director.all %}
                                {{ movie.title }}
                            {% endfor %}
                        </span></li>
                    <li><span><b>Актеры:</b>
                            {% for movie in actor.film_actor.all %}
                                {{ movie.title }}
                            {% endfor %}
                        </span>
                    </li>
        </div>
        <div class="row sub-para-w3layouts mt-5">

            <h3 class="shop-sing editContent">
                О {{ actor.name }}
            </h3>
            <p class="editContent">
                {{ actor.description|safe }}
            </p>
        </div>
        <hr>
    </div>
{% endblock %}

movie/templates/html/movies.html
{% extends 'html/layout.html' %}

{% block title %}Главная страница{% endblock %}

{% block content %}
                    <!-- //product left -->
                    <!-- product right -->
                    <div class="left-ads-display col-lg-9">
                        <div class="row">
                            {% for i in movie_list %}
                            <div class="col-md-4 product-men">
                                <div class="product-shoe-info editContent text-center mt-lg-4" >
                                    <div class="men-thumb-item">
                                        <img src="{{ i.poster.url }}" class="img-fluid" alt="" >
                                    </div>
                                    <div class="item-info-product">
                                        <h4 class="">
                                            <a href="{{ i.get_absolute_url }}" class="editContent" >{{ i.title }}</a>
                                        </h4>

                                        <div class="product_price">
                                            <div class="grid-price">
                                                <span class="money editContent" >{{ i.tagline }}</span>
                                            </div>
                                        </div>

                                        <ul class="stars">
                                            <li><a href="#"><span class="fa fa-star" aria-hidden="true" ></span></a></li>
                                            <li><a href="#"><span class="fa fa-star" aria-hidden="true" ></span></a></li>
                                            <li><a href="#"><span class="fa fa-star-half-o" aria-hidden="true" ></span></a></li>
                                            <li><a href="#"><span class="fa fa-star-half-o" aria-hidden="true" ></span></a></li>
                                            <li><a href="#"><span class="fa fa-star-o" aria-hidden="true" ></span></a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        <!--<div class="grid-img-right mt-4 text-right bg bg1" >
                            <span class="money editContent" >Flat 50% Off</span>
                            <a href="moviesingle.html" class="btn" >Now</a>
                        </div>-->
                    </div>
{% endblock %}

movie/templates/html/moviesingle.html
{% extends 'html/layout.html' %}
{% load static %}
{% block title %}Главная страница{% endblock %}

{% block banner %}
<div class="main-banner bg bg1" id="home" style="background-color: rgba(0, 0, 0, 0); margin-top: 0px; background-image:
  url('../static/images/banner.jpg');">
{% endblock %}

{% block content %}

                <!-- //product left -->
                <!-- product right -->
    <div class="left-ads-display col-lg-8">
        <div class="row">
            <div class="desc1-left col-md-6">
                <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <h3 class="editContent" style="outline: none; cursor: inherit;">
                    {{ movie.title }}</h3>
                <h5 class="editContent"></h5>
                <ul>
                    <li style="list-style: none"><span><b>Год:</b>{{ movie.year }}</span></li>
                    <li style="list-style: none"><span><b>Страна:</b>{{ movie.country }}</span>
                    </li>
                    <li style="list-style: none"><span><b>Слоган:</b>{{ movie.tagline }}</span>
                    </li>
                    <li style="list-style: none">
                        <span><b>Режиссер:</b>
                            {% for director in movie.directors.all %}
                                <a href="{{director.get_absolute_url}}">
                                    {{ director.name }}</a>
                            {% endfor %}
                        </span></li>
                    <li style="list-style: none">
                        <span><b>Актеры:</b>
                            {% for actor in movie.actors.all %}
                                <a href="{{actor.get_absolute_url}}">
                                    {{ actor.name }}</a>
                            {% endfor %}
                        </span>
                    </li>
                    <li style="list-style: none"><span><b>Жанр:</b>
                        {% for genres in movie.genre.all %}
                            {{ genres.name }}
                        {% endfor %}</span>
                    </li>
                    <li style="list-style: none"><span><b>Премьера в мире:</b>{{ movie.world_premiere }}</span>
                    </li>
                    <li style="list-style: none">
                        <span><b>Бюджет:</b>${{ movie.budget }}</span></li>
                    <li style="list-style: none">
                        <span><b>Сборы в США:</b>${{ movie.fees_to_usa }}</span></li>
                    <li style="list-style: none">
                        <span><b>Сборы в мире:</b>${{ movie.fees_to_world }}</span>
                    </li>
                    <li style="list-style: none">
                        <a href="#"><b>Рейтинг:</b>
                            <span class="fa fa-star" aria-hidden="true"
                            ></span>
                            <span class="fa fa-star" aria-hidden="true"
                            ></span>
                            <span class="fa fa-star" aria-hidden="true"
                            ></span>
                            <span class="fa fa-star" aria-hidden="true"
                            ></span>
                            <span class="fa fa-star" aria-hidden="true"
                            ></span>
                            <span class="editContent"
                            >5.0</span>
                        </a>
                    </li>
                    <div class="share-desc">
                        <div class="share">
                            <h4 class="editContent">
                                Share:</h4>
                            <ul class="w3layouts_social_list list-unstyled">
                                <li>
                                    <a href="#" class="w3pvt_facebook editContent">
                                        <span class="fa fa-facebook-f"></span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="w3pvt_twitter editContent">
                                        <span class="fa fa-twitter"></span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="w3pvt_dribble editContent">
                                        <span class="fa fa-dribbble"></span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="clearfix"></div>
                    </div>
            </div>
        </div>
        <div class="row sub-para-w3layouts mt-5">

            <h3 class="shop-sing editContent">
                О фильме {{ movie.title }}
            </h3>
            <p>
                {% for image in movie.movieshots_set.all %}
                    <img src="{{ image.image.url }}" class="img-movie-shots "
                         alt="{{ image.description }}">
                {% endfor %}
            </p>
            <p class="editContent">
                {{ movie.description|safe }}
            </p>
<!--            <p class="mt-3 italic-blue editContent">-->
<!--                <iframe width="560" height="315"-->
<!--                        src="https://www.youtube.com/embed/A36LahZNUiE?controls=0"-->
<!--                        frameborder="0" allow="accelerometer; autoplay;-->
<!--                                                               encrypted-media; gyroscope; picture-in-picture"-->
<!--                        allowfullscreen>-->
<!--                </iframe>-->
<!--            </p>-->
        </div>
        <hr>
        <div class="row">
            <div class="single-form-left">
                <!-- contact form grid -->
                <div class="contact-single">
                    <h3 class="editContent">
                        <span class="sub-tittle editContent">{{ movie.reviews_set.count }}</span>Оставить
                        отзыв</h3>
                    <form action="{% url 'add_review' movie.id %}" method="post" class="mt-4"
                          id="formReview">
                        {% csrf_token %}
                        <input type="hidden" name="parent" id="contactparent" value="">
                        <div class="form-group editContent">
                            <label for="contactcomment" class="editContent">
                                Ваш комментарий *
                            </label>
                            <textarea class="form-control border" rows="5" name="text"
                                      id="contactcomment" required=""></textarea>
                        </div>
                        <div class="d-sm-flex">
                            <div class="col-sm-6 form-group p-0 editContent">
                                <label for="contactusername" class="editContent">
                                    Имя *
                                </label>
                                <input type="text" class="form-control border" name="name"
                                       id="contactusername" required="">
                            </div>
                            <div class="col-sm-6 form-group ml-sm-3 editContent">
                                <label for="contactemail" class="editContent">
                                    Email *
                                </label>
                                <input type="email" class="form-control border" name="email"
                                       id="contactemail" required="">
                            </div>
                        </div>
                        <button type="submit"
                                class="mt-3 btn btn-success btn-block py-3">
                            Отправить
                        </button>
                    </form>
                </div>
                <!--  //contact form grid ends here -->
            </div>
        </div>
        {% for i in movie.reviews.all %}
            <div class="media py-5">
                <img src="{% static 'images/te2.jpg' %}" class="mr-3 img-fluid" alt="image">
                <div class="media-body mt-4">
                    <h5 class="mt-0 editContent">
                        {{ i.name }}
                    </h5>
                    <p class="mt-2 editContent">
                        {{ i.text }}
                    </p>
                    <a href="#formReview"
                       onclick="addReview('{{ i.name }}', '{{ i.id }}')">Ответить</a>
                    {% for l in review.review_set.all %}
                        <div class="media mt-5 editContent">
                            <a class="pr-3" href="#">
                                <img src="{% static 'images/te2.jpg' %}" class="img-fluid "
                                     alt="image">
                            </a>
                            <div class="media-body">
                                <h5 class="mt-0 editContent">{{ l.name }}</h5>
                                <p class="mt-2 editContent">{{ l.text }}</p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
    </div>
    </div>
    <script>
        function addReview(name, id) {
            document.getElementById("contactparent").value = id;
            document.getElementById("contactcomment").innerText = `${name}, `
        }
    </script>
{% endblock %}

movie/templates/html/tags/last_movie.html
<div class="deal-leftmk left-side">
    {% load movie_tag %}
    <h3 class="sear-head editContent">
        Последние добавленные</h3>
    {% for movie in last_movies %}
        <div class="special-sec1 row mt-3 editContent">
            <div class="img-deals col-md-4">
                <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
            </div>
        </div>
        <div class="img-deal1 col-md-4">
            <h3 class="editContent">{{ movie.title }}</h3>
            <a href="{{ movie.get_absolute_url }}" class="editContent"
               style="outline: none; cursor: inherit;"></a>
        </div>
    {% endfor %}
</div>

movie/templates/movies/movie_list.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {% for i in movie_list %}
        {{ i.title }}
    {% endfor %}
</body>
</html>